const state={todos:JSON.parse(localStorage.getItem('universyn-todos')||'[]'),notes:localStorage.getItem('universyn-notes')||'',seconds:1500,timer:null};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const toolNames={pomodoro:'Pomodoro',todo:'Lista de tarefas',notes:'Notas rápidas',calculator:'Calculadora'};
function save(){localStorage.setItem('universyn-todos',JSON.stringify(state.todos));localStorage.setItem('universyn-notes',state.notes);updateCount()}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function updateCount(){$('#completed-count').textContent=12+state.todos.filter(t=>t.done).length}
function openTool(type){$('#modal-title').textContent=toolNames[type]||'Ferramenta';$('#modal-body').innerHTML=toolMarkup(type);$('#modal-backdrop').hidden=false;document.body.style.overflow='hidden';initTool(type);}
function closeTool(){$('#modal-backdrop').hidden=true;document.body.style.overflow='';if(state.timer){clearInterval(state.timer);state.timer=null}}
function toolMarkup(type){if(type==='todo')return `<form id="todo-form"><input class="field" id="todo-input" placeholder="O que precisa ser feito?" autocomplete="off"><button class="modal-btn">Adicionar tarefa</button></form><div id="todo-list" style="margin-top:18px"></div>`;
if(type==='pomodoro')return `<p style="text-align:center;color:#858899;font-size:12px">25 minutos de foco. Você consegue.</p><div class="timer" id="timer">25:00</div><div class="timer-actions"><button class="modal-btn" id="start-timer">Iniciar foco</button><button class="secondary-btn" id="pause-timer">Pausar</button><button class="secondary-btn" id="reset-timer">Recomeçar</button></div>`;
if(type==='notes')return `<textarea class="field notes" id="notes-input" placeholder="Escreva uma ideia, resumo ou lembrete...">${escapeHtml(state.notes)}</textarea><p style="font-size:11px;color:#a0a2b1">Suas notas são salvas automaticamente neste dispositivo.</p>`;
return `<input class="field calc-display" id="calc-display" readonly value=""><div class="calc-grid">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','C','+','(',')','⌫','='].map(k=>`<button type="button" data-calc="${k}">${k}</button>`).join('')}</div>`}
function escapeHtml(text){return text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function initTool(type){if(type==='todo'){renderTodos();$('#todo-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#todo-input');if(!input.value.trim())return;state.todos.push({text:input.value.trim(),done:false});input.value='';save();renderTodos();toast('Tarefa adicionada')})}if(type==='notes')$('#notes-input').addEventListener('input',e=>{state.notes=e.target.value;save()});if(type==='pomodoro'){updateTimer();$('#start-timer').onclick=()=>{if(!state.timer)state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0){clearInterval(state.timer);state.timer=null;toast('Sessão concluída. Bom trabalho!');state.seconds=1500;updateTimer()}},1000)};$('#pause-timer').onclick=()=>{clearInterval(state.timer);state.timer=null};$('#reset-timer').onclick=()=>{clearInterval(state.timer);state.timer=null;state.seconds=1500;updateTimer()}}if(type==='calculator')initCalculator()}
function renderTodos(){const list=$('#todo-list');if(!list)return;list.innerHTML=state.todos.length?state.todos.map((t,i)=>`<div class="todo-row ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-todo="${i}"><span>${escapeHtml(t.text)}</span><button data-remove="${i}" aria-label="Remover tarefa">×</button></div>`).join(''):'<p style="font-size:12px;color:#a0a2b1;text-align:center;padding:20px 0">Nenhuma tarefa por aqui.</p>';list.querySelectorAll('[data-todo]').forEach(x=>x.onchange=()=>{state.todos[+x.dataset.todo].done=x.checked;save();renderTodos()});list.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.todos.splice(+x.dataset.remove,1);save();renderTodos()})}
function updateTimer(){const el=$('#timer');if(el)el.textContent=`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`}
function initCalculator(){const d=$('#calc-display');$('#modal-body').addEventListener('click',e=>{const key=e.target.dataset.calc;if(!key)return;if(key==='C')d.value='';else if(key==='⌫')d.value=d.value.slice(0,-1);else if(key==='='){try{if(!/^[0-9+*/().\- ]+$/.test(d.value))throw Error();d.value=String(Function(`"use strict";return (${d.value})`)())}catch{d.value='Erro'}}else d.value+=key==='÷'?'/':key==='×'?'*':key==='−'?'-':key})}
function init(){const now=new Date();$('#current-date').textContent=now.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'});updateCount();$$('[data-open-tool]').forEach(btn=>btn.addEventListener('click',()=>openTool(btn.dataset.openTool)));$('#close-modal').onclick=closeTool;$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeTool()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal-backdrop').hidden)closeTool()});$('#tool-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('[data-tool-card]').forEach(card=>card.style.display=card.dataset.name.includes(q)?'flex':'none')});$('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');$$('.nav-link[href^="#"]').forEach(link=>link.addEventListener('click',()=>$('.sidebar').classList.remove('open')));$('#add-event').onclick=()=>toast('Agenda inteligente em breve');$('#reset-data').onclick=()=>{if(confirm('Limpar tarefas e notas salvas?')){state.todos=[];state.notes='';save();toast('Dados locais limpos')}}}
document.addEventListener('DOMContentLoaded',init);
